In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

In [3]:
pd.__version__

'1.4.2'

In [4]:
laptops=pd.read_csv('laptops.csv')


In [5]:
laptops.count()

Laptop          2160
Status          2160
Brand           2160
Model           2160
CPU             2160
RAM             2160
Storage         2160
Storage type    2118
GPU              789
Screen          2156
Touch           2160
Final Price     2160
dtype: int64

In [22]:
laptops['Brand'].nunique()

27

In [7]:
laptops.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [8]:
dell=laptops[laptops['Brand']=='Dell']
dell['Final Price'].max()

3936.0

In [9]:
print(laptops['Screen'].median())

print(laptops['Screen'].mode())


15.6
0    15.6
Name: Screen, dtype: float64


In [10]:
laptops['Screen'].fillna

<bound method Series.fillna of 0       15.6
1       15.6
2       15.6
3       15.6
4       15.6
        ... 
2155    17.3
2156    17.3
2157    17.3
2158    13.4
2159    13.4
Name: Screen, Length: 2160, dtype: float64>

In [11]:
print(laptops['Screen'].median())

print(laptops['Screen'].mode())

15.6
0    15.6
Name: Screen, dtype: float64


In [12]:
Innjoo=laptops[laptops['Brand']=='Innjoo']
Innjoo[['RAM','Storage','Screen']]

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [13]:
X = np.array(Innjoo[['RAM','Storage','Screen']])

In [14]:
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [15]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [16]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [17]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [18]:
XTX=matrix_matrix_multiplication(X.T,X)

In [19]:
np.linalg.inv(XTX)

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [20]:
y = np.array([1100,1300,800,900,1000,1100])

In [21]:
w=(np.linalg.inv(XTX).dot(X.T)).dot(y)
w

array([45.58076606,  0.42783519, 45.29127938])